# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Tomer\PycharmProjects\Pyqt5_improved_framework\Tomer_To_Git\ui_screen_files\add_new_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewProfileWindow(object):
    def setupUi(self, AddNewProfileWindow):
        AddNewProfileWindow.setObjectName("AddNewProfileWindow")
        AddNewProfileWindow.resize(890, 640)
        self.centralwidget = QtWidgets.QWidget(AddNewProfileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(390, 30, 111, 41))
        self.title.setObjectName("title")
        self.name_box = QtWidgets.QTextEdit(self.centralwidget)
        self.name_box.setGeometry(QtCore.QRect(380, 80, 151, 41))
        self.name_box.setObjectName("name_box")
        self.last_name_box = QtWidgets.QTextEdit(self.centralwidget)
        self.last_name_box.setGeometry(QtCore.QRect(380, 140, 151, 41))
        self.last_name_box.setObjectName("last_name_box")
        self.id_box = QtWidgets.QTextEdit(self.centralwidget)
        self.id_box.setGeometry(QtCore.QRect(380, 200, 151, 41))
        self.id_box.setObjectName("id_box")
        self.phone_box = QtWidgets.QTextEdit(self.centralwidget)
        self.phone_box.setGeometry(QtCore.QRect(380, 260, 151, 41))
        self.phone_box.setObjectName("phone_box")
        self.address_box = QtWidgets.QTextEdit(self.centralwidget)
        self.address_box.setGeometry(QtCore.QRect(380, 320, 151, 41))
        self.address_box.setObjectName("address_box")
        self.city_box = QtWidgets.QTextEdit(self.centralwidget)
        self.city_box.setGeometry(QtCore.QRect(380, 380, 151, 41))
        self.city_box.setObjectName("city_box")
        self.upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_btn.setGeometry(QtCore.QRect(410, 430, 93, 41))
        self.upload_btn.setObjectName("upload_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(70, 520, 121, 51))
        self.back_btn.setObjectName("back_btn")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(690, 520, 121, 51))
        self.add_btn.setObjectName("add_btn")
        self.title_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_2.setGeometry(QtCore.QRect(250, 80, 111, 41))
        self.title_2.setObjectName("title_2")
        self.title_3 = QtWidgets.QLabel(self.centralwidget)
        self.title_3.setGeometry(QtCore.QRect(250, 140, 111, 41))
        self.title_3.setObjectName("title_3")
        self.title_4 = QtWidgets.QLabel(self.centralwidget)
        self.title_4.setGeometry(QtCore.QRect(250, 200, 111, 41))
        self.title_4.setObjectName("title_4")
        self.title_5 = QtWidgets.QLabel(self.centralwidget)
        self.title_5.setGeometry(QtCore.QRect(250, 260, 111, 41))
        self.title_5.setObjectName("title_5")
        self.title_6 = QtWidgets.QLabel(self.centralwidget)
        self.title_6.setGeometry(QtCore.QRect(250, 320, 111, 41))
        self.title_6.setObjectName("title_6")
        self.title_7 = QtWidgets.QLabel(self.centralwidget)
        self.title_7.setGeometry(QtCore.QRect(250, 380, 111, 41))
        self.title_7.setObjectName("title_7")
        self.path_box = QtWidgets.QTextEdit(self.centralwidget)
        self.path_box.setGeometry(QtCore.QRect(320, 480, 271, 31))
        self.path_box.setObjectName("path_box")
        AddNewProfileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddNewProfileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menubar.setObjectName("menubar")
        AddNewProfileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddNewProfileWindow)
        self.statusbar.setObjectName("statusbar")
        AddNewProfileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(AddNewProfileWindow)

    def retranslateUi(self, AddNewProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        AddNewProfileWindow.setWindowTitle(_translate("AddNewProfileWindow", "MainWindow"))
        self.title.setText(_translate("AddNewProfileWindow", "Add New Profile"))
        self.upload_btn.setText(_translate("AddNewProfileWindow", "Upload Record"))
        self.back_btn.setText(_translate("AddNewProfileWindow", "Back"))
        self.add_btn.setText(_translate("AddNewProfileWindow", "Add"))
        self.title_2.setText(_translate("AddNewProfileWindow", "Name :"))
        self.title_3.setText(_translate("AddNewProfileWindow", "Last Name :"))
        self.title_4.setText(_translate("AddNewProfileWindow", "ID :"))
        self.title_5.setText(_translate("AddNewProfileWindow", "Phone :"))
        self.title_6.setText(_translate("AddNewProfileWindow", "Address :"))
        self.title_7.setText(_translate("AddNewProfileWindow", "City :"))
        self.path_box.setHtml(_translate("AddNewProfileWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Record Path</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewProfileWindow = QtWidgets.QMainWindow()
    ui = Ui_AddNewProfileWindow()
    ui.setupUi(AddNewProfileWindow)
    AddNewProfileWindow.show()
    sys.exit(app.exec_())
