# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Tomer\PycharmProjects\Pyqt5_improved_framework\Tomer_To_Git\ui_screen_files\message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageWindow(object):
    def setupUi(self, MessageWindow):
        MessageWindow.setObjectName("MessageWindow")
        MessageWindow.resize(495, 278)
        font = QtGui.QFont()
        font.setPointSize(14)
        MessageWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MessageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(90, 50, 331, 131))
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        MessageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MessageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 37))
        self.menubar.setObjectName("menubar")
        MessageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MessageWindow)
        self.statusbar.setObjectName("statusbar")
        MessageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MessageWindow)
        QtCore.QMetaObject.connectSlotsByName(MessageWindow)

    def retranslateUi(self, MessageWindow):
        _translate = QtCore.QCoreApplication.translate
        MessageWindow.setWindowTitle(_translate("MessageWindow", "MainWindow"))
        self.messageLabel.setText(_translate("MessageWindow", "messageLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MessageWindow = QtWidgets.QMainWindow()
    ui = Ui_MessageWindow()
    ui.setupUi(MessageWindow)
    MessageWindow.show()
    sys.exit(app.exec_())
