# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Tomer\PycharmProjects\Pyqt5_improved_framework\Tomer_To_Git\ui_screen_files\profiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilesWindow(object):
    def setupUi(self, ProfilesWindow):
        ProfilesWindow.setObjectName("ProfilesWindow")
        ProfilesWindow.resize(895, 567)
        self.centralwidget = QtWidgets.QWidget(ProfilesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 30, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 110, 761, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 480, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        ProfilesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProfilesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 26))
        self.menubar.setObjectName("menubar")
        ProfilesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProfilesWindow)
        self.statusbar.setObjectName("statusbar")
        ProfilesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProfilesWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfilesWindow)

    def retranslateUi(self, ProfilesWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfilesWindow.setWindowTitle(_translate("ProfilesWindow", "MainWindow"))
        self.label.setText(_translate("ProfilesWindow", "Profiles"))
        self.pushButton.setText(_translate("ProfilesWindow", "Add New Profile"))
        self.pushButton_2.setText(_translate("ProfilesWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfilesWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfilesWindow()
    ui.setupUi(ProfilesWindow)
    ProfilesWindow.show()
    sys.exit(app.exec_())
