# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Tomer\PycharmProjects\Pyqt5_improved_framework\Tomer_To_Git\ui_screen_files\speaker_distribution.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeakerDistributionWindow(object):
    def setupUi(self, SpeakerDistributionWindow):
        SpeakerDistributionWindow.setObjectName("SpeakerDistributionWindow")
        SpeakerDistributionWindow.resize(895, 567)
        self.centralwidget = QtWidgets.QWidget(SpeakerDistributionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(220, 120, 471, 301))
        self.graphicsView.setObjectName("graphicsView")
        SpeakerDistributionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpeakerDistributionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 26))
        self.menubar.setObjectName("menubar")
        SpeakerDistributionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpeakerDistributionWindow)
        self.statusbar.setObjectName("statusbar")
        SpeakerDistributionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SpeakerDistributionWindow)
        QtCore.QMetaObject.connectSlotsByName(SpeakerDistributionWindow)

    def retranslateUi(self, SpeakerDistributionWindow):
        _translate = QtCore.QCoreApplication.translate
        SpeakerDistributionWindow.setWindowTitle(_translate("SpeakerDistributionWindow", "MainWindow"))
        self.label.setText(_translate("SpeakerDistributionWindow", "Speaker Distribution"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpeakerDistributionWindow = QtWidgets.QMainWindow()
    ui = Ui_SpeakerDistributionWindow()
    ui.setupUi(SpeakerDistributionWindow)
    SpeakerDistributionWindow.show()
    sys.exit(app.exec_())
